### ISSUE TITLE
invalid character 'C' looking for beginning of value

### ISSUE THREAD

**Issue by PieterGit** [ecc1/backfill#1]
When I run backfill.go I get:
$ ./backfill
2016/12/28 10:47:19 retrieving Nightscout records from last 1h0m0.000000625s
2016/12/28 10:47:20 invalid character 'C' looking for beginning of value

This is my fist Go project, so I don't know what is causing this. 
I assume it's the reading of the Dexcom G4 that causes errors.
Can you help me debug this issue/bug?

**Comment by PieterGit** [comment]
Found the problem myself! I had a trailing slash to the NIGHTSCOUT_SITE url.
Why do you use NIGHTSCOUT_SITE instead of NIGHTSCOUT_HOST btw
Same for NIGHTSCOUT_API_SECRET instead of API_SECRET

Should I close this issue, or do you want to add a check in the nightscout package to warn the user. My Go skills don't make that happen yet.

**Comment by ecc1** [comment]
Thanks for tracking this down. I'll try to make the error message clearer (or just work properly in that case) so please leave this open.On Dec 28, 2016 12:14 AM, PieterGit <notifications@github.com> wrote:Found the problem myself! I had a trailing slash to the NIGHTSCOUT_SITE url.
Why do you use NIGHTSCOUT_SITE instead of NIGHTSCOUT_HOST btw
Same for NIGHTSCOUT_API_SECRET instead of API_SECRET
Should I close this issue, or do you want to add a check in the nightscout package to warn the user. My Go skills don't make that happen yet.

**Comment by ecc1** [comment]
This should be fixed now in https://github.com/ecc1/nightscout/commit/d089f563a2c574667a9d196658477983db010ddf
